import 'package:flutter/material.dart';
import 'package:flutter_email_sender/flutter_email_sender.dart';
import 'package:flutter/services.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:flutter/foundation.dart';
import '../models/inspection.dart';
import '../models/user.dart';
import '../services/auth_service.dart';
import 'dart:io'; // <- TOP (only used for mobile)
import 'dart:convert'; // for base64
import 'dart:typed_data';
// For web ZIP download
// import 'package:archive/archive.dart';
// import 'package:universal_html/html.dart' as html;

class EmailReportScreen extends StatefulWidget {
  final Inspection inspection;
  final bool isDetailed;

  const EmailReportScreen({
    super.key,
    required this.inspection,
    this.isDetailed = false,
  });

  @override
  State<EmailReportScreen> createState() => _EmailReportScreenState();
}

class _EmailReportScreenState extends State<EmailReportScreen> {
  final _formKey = GlobalKey<FormState>();
  final _recipientsController = TextEditingController();
  final _subjectController = TextEditingController();
  final _bodyController = TextEditingController();
  final _ccController = TextEditingController();
  final _bccController = TextEditingController();
  
  bool _isLoading = false;
  User? _currentUser;

  @override
  void initState() {
    super.initState();
    _initializeData();
  }

  @override
  void dispose() {
    _recipientsController.dispose();
    _subjectController.dispose();
    _bodyController.dispose();
    _ccController.dispose();
    _bccController.dispose();
    super.dispose();
  }

  Future<void> _initializeData() async {
    try {
      final user = await AuthService.getCurrentUser();
      setState(() {
        _currentUser = user;
      });
      
      // Pre-fill form with inspection data
      _subjectController.text = _buildEmailSubject();
      
      if (kIsWeb) {
        _bodyController.text = widget.isDetailed ? _generateTextReport(detailed: true) : _generateTextReport(detailed: false);
      } else {
        _bodyController.text = await (widget.isDetailed ? _generateHtmlReport(detailed: true) : _generateHtmlReport(detailed: false));
      }
      
      // Pre-fill recipient with a default email if needed
      // Note: User model doesn't have email field, so we leave recipients empty for user to fill
      
      // Pre-fill CC with your email to ensure you get copies
      _ccController.text = 'anthony.capuyan23@gmail.com';
    } catch (e) {
      print('Error initializing email data: $e');
    }
  }

  String _generateQuickReport() {
    final inspectorName = _currentUser?.name ?? 'Unknown Inspector';
    final createdDate = _formatDateTime(widget.inspection.createdAt);
    
    // Quick status check
    final sectionStatuses = widget.inspection.sectionStatus.values.toList();
    final hasInProgress = sectionStatuses.contains('in_progress');
    final hasPassed = sectionStatuses.contains('passed');
    final hasNotPassed = sectionStatuses.contains('not_passed');
    
    String status = 'No sections';
    if (sectionStatuses.isNotEmpty) {
      if (hasInProgress) status = 'In Progress';
      else if (hasPassed || hasNotPassed) status = 'Completed';
    }
    
    // Count completed sections
    int completedSections = 0;
    if (widget.inspection.mechanicalRemarks.isNotEmpty || widget.inspection.mechanicalAssessment.isNotEmpty) completedSections++;
    if (widget.inspection.lineGradeRemarks.isNotEmpty || widget.inspection.lineGradeAssessment.isNotEmpty) completedSections++;
    if (widget.inspection.architecturalRemarks.isNotEmpty || widget.inspection.architecturalAssessment.isNotEmpty) completedSections++;
    if (widget.inspection.civilStructuralRemarks.isNotEmpty || widget.inspection.civilStructuralAssessment.isNotEmpty) completedSections++;
    if (widget.inspection.sanitaryPlumbingRemarks.isNotEmpty || widget.inspection.sanitaryPlumbingAssessment.isNotEmpty) completedSections++;
    if (widget.inspection.electricalElectronicsRemarks.isNotEmpty || widget.inspection.electricalElectronicsAssessment.isNotEmpty) completedSections++;
    
    return '''INSPECTION REPORT SUMMARY

Inspection ID: ${widget.inspection.id.substring(widget.inspection.id.length - 8)}
Inspector: $inspectorName
Date: $createdDate
Status: $status
Sections Completed: $completedSections/6
Photos: ${widget.inspection.imagePaths.length}
Videos: ${widget.inspection.videoPaths.length}
Sync Status: ${widget.inspection.isSynced ? 'Synced' : 'Pending'}

Business ID:
${widget.inspection.scannedData}

Location: ${widget.inspection.latitude != null && widget.inspection.longitude != null 
  ? 'Lat: ${widget.inspection.latitude!.toStringAsFixed(6)}, Lng: ${widget.inspection.longitude!.toStringAsFixed(6)}' 
  : 'Not available'}

---
Office of Building Official - Ormoc City
Generated by OBO Mobile Inspector App

For detailed inspection data, please refer to the mobile application.''';
  }

  String _buildEmailSubject() {
    final qrData = widget.inspection.scannedData.toString().trim();
    return 'business id inspected: ${qrData.isNotEmpty ? qrData : ''}'.trim();
  }

  Future<String> _generateHtmlReport({required bool detailed}) async {
    final inspectorName = _currentUser?.name ?? 'Unknown Inspector';
    final createdDate = _formatDateTime(widget.inspection.createdAt);
    final hasLocation = widget.inspection.latitude != null && widget.inspection.longitude != null;
    final locationInfo = hasLocation
        ? 'Lat: ${widget.inspection.latitude!.toStringAsFixed(6)}, Lng: ${widget.inspection.longitude!.toStringAsFixed(6)}'
        : 'Not available';
    final mapsUrl = hasLocation
        ? 'https://www.google.com/maps/search/?api=1&query=${widget.inspection.latitude!.toStringAsFixed(6)},${widget.inspection.longitude!.toStringAsFixed(6)}'
        : '';
    final idShort = widget.inspection.id.substring(widget.inspection.id.length - 8);

    // Build sections in HTML
    String sectionsHtml = '';
    void addSection(String title, String remarks, String assessment) {
      if (remarks.isEmpty && assessment.isEmpty) return;
      sectionsHtml += '<tr><td style="padding:8px 12px; border:1px solid #e5e7eb;"><strong>$title</strong><div style="color:#374151; font-size:13px;">';
      if (remarks.isNotEmpty) sectionsHtml += '<div>Remarks: ${_escapeHtml(remarks)}</div>';
      if (assessment.isNotEmpty) sectionsHtml += '<div>Assessment: ${_escapeHtml(assessment)}</div>';
      sectionsHtml += '</div></td></tr>';
    }
    addSection('Mechanical', widget.inspection.mechanicalRemarks, widget.inspection.mechanicalAssessment);
    addSection('Line and Grade', widget.inspection.lineGradeRemarks, widget.inspection.lineGradeAssessment);
    addSection('Architectural', widget.inspection.architecturalRemarks, widget.inspection.architecturalAssessment);
    addSection('Civil/Structural', widget.inspection.civilStructuralRemarks, widget.inspection.civilStructuralAssessment);
    addSection('Sanitary/Plumbing', widget.inspection.sanitaryPlumbingRemarks, widget.inspection.sanitaryPlumbingAssessment);
    addSection('Electrical/Electronics', widget.inspection.electricalElectronicsRemarks, widget.inspection.electricalElectronicsAssessment);
    if (sectionsHtml.isEmpty) {
      sectionsHtml = '<tr><td style="padding:12px; border:1px solid #e5e7eb;">No inspection sections were completed.</td></tr>';
    }

    // Media lists (note: attached to email on mobile; web cannot auto-attach)
    final imageHtmls = await _inlineImageHtmlList();
    final videoHtmls = await _inlineVideoList();

    final mediaHtml = '''
      <div style="margin-top:8px; font-size:14px; color:#222;">
        <div><b>Photos (${widget.inspection.imagePaths.length}):</b>
        ${imageHtmls.isNotEmpty ? imageHtmls.join('') : '<span style="color:#aaa">None</span>'}
        </div>
        <div style="margin-top:7px;"><b>Videos (${widget.inspection.videoPaths.length}):</b><br/>
        ${videoHtmls.isNotEmpty ? videoHtmls.join('') : '<span style=\"color:#aaa\">None</span>'}
        </div>
        <div style="margin-top:8px; background:#fffbe8; padding:8px 12px; border-radius:6px; border:1px solid #fde68a; color:#b45309; font-size:12px;">
          <span style="font-weight:bold;">Attachment Info:</span><br/>
          • <b>Mobile app</b>: images/videos are also attached.<br/>
          • <b>Web</b>: Inline previews shown; use 'Download All Media' to speed up attachment.
        </div>
        <!-- ZIP BUTTON PLACEHOLDER, IMPLEMENT in UI for web -->
      </div>
    ''';

    // Build final HTML
    final cityLogo = 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Ormoc_City_Seal.png'; // Placeholder logo
    final headerColor = '#2467b2';
    final sectionHeaderColor = '#f4f8fb';
    final borderColor = '#e2e8f0';
    final accentColor = '#10B981';
    final fontFamily = "'Segoe UI', Helvetica, Arial, sans-serif";
    return '''
<div style="font-family:$fontFamily; color:#111827; background:$sectionHeaderColor; padding:0; width:100%">
  <div style="max-width:600px; margin:32px auto; background:#fff; border:1px solid $borderColor; border-radius:12px; overflow:hidden; box-shadow:0 4px 32px #0001;">
    <div style="background:$headerColor; padding:24px 24px 16px 24px; display:flex; align-items:center;">
      <img src="$cityLogo" alt="Ormoc City Logo" onerror="this.style.display='none'" style="width:56px; height:56px; margin-right:20px; border-radius:50%; box-shadow:0 2px 6px #0002;"> 
      <div>
        <h1 style="margin:0; color:#fff; font-size:26px; letter-spacing:0.5px; font-weight:700;">Ormoc City<br>Building Official Inspection</h1>
        <div style="margin-top:4px; color:#d1fae5; font-size:13px; font-weight:400">OBO Mobile Inspector App</div>
      </div>
    </div>
    <div style="padding:28px 24px 12px 24px;">
      <div style="margin-bottom:18px; color:$headerColor; font-size:18px; font-weight:bold; letter-spacing:1px;">Inspection Report</div>
      <div style="font-size:13px; color:#374151; margin-bottom:10px;">Report ID: $idShort · Inspector: ${_escapeHtml(inspectorName)}<br>Date: $createdDate</div>
      <div style="font-size:13px; color:#374151;">Business ID: ${_escapeHtml(widget.inspection.scannedData.toString())}</div>
      <div style="margin-top:5px; font-size:13px; color:#374151;">Location: ${_escapeHtml(locationInfo)}${hasLocation ? ' · <a href="$mapsUrl" style="color:$accentColor; text-decoration:underline;">Open in Maps</a>' : ''}</div>
      <div style="height:16px;"></div>
      <table style="border-collapse:collapse; width:100%; background:#fafcff; border:1px solid $borderColor; border-radius:10px; overflow:hidden;">
    <thead>
          <tr style="background:$sectionHeaderColor;">
            <th style="text-align:left; padding:13px 14px; border-bottom:1px solid $borderColor; color:#194b8c; font-size:15px; letter-spacing:1px; font-weight:600;">Inspection Sections</th>
          </tr>
    </thead>
    <tbody>
      $sectionsHtml
    </tbody>
  </table>
      <div style="height:18px"></div>
      <div style="background:#fdfcff; border:1px solid $borderColor; border-radius:8px; padding:15px 18px;">$mediaHtml</div>
      <div style="margin-top:18px; font-size:13px; color:#666;">Generated by <b>OBO Mobile Inspector App</b> - Ormoc City, Office of Building Official</div>
      <div style="margin-top:8px; font-size:12px; color:#aaa;">Contact: obo-support@ormoc.gov.ph</div>
    </div>
  </div>
</div>
''';
  }

  String _generateTextReport({required bool detailed}) {
    // Use existing builders but ensure plain text
    final base = detailed ? _generateDetailedReport() : _generateQuickReport();
    final images = widget.inspection.imagePaths.map((p) => '- ${_basename(p)}').join('\n');
    final videos = widget.inspection.videoPaths.map((p) => '- ${_basename(p)}').join('\n');
    // Add Google Maps link if available
    String maps = '';
    if (widget.inspection.latitude != null && widget.inspection.longitude != null) {
      final lat = widget.inspection.latitude!.toStringAsFixed(6);
      final lng = widget.inspection.longitude!.toStringAsFixed(6);
      maps = '\nGoogle Maps: https://www.google.com/maps/search/?api=1&query=' + lat + ',' + lng;
    }
    return base + '\n\nPHOTOS (${widget.inspection.imagePaths.length})\n${images.isEmpty ? 'None' : images}'
        + '\n\nVIDEOS (${widget.inspection.videoPaths.length})\n${videos.isEmpty ? 'None' : videos}'
        + maps
        + '\n\nNote: On web, please attach media manually.';
  }

  String _escapeHtml(String input) {
    return input
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;');
  }

  String _basename(String path) {
    final idx = path.replaceAll('\\\\', '/').lastIndexOf('/');
    return idx >= 0 ? path.substring(idx + 1) : path;
  }

  String _generateDetailedReport() {
    final currentDate = DateTime.now();
    final inspectorName = _currentUser?.name ?? 'Unknown Inspector';
    
    // Format dates
    final createdDate = _formatDateTime(widget.inspection.createdAt);
    final updatedDate = _formatDateTime(widget.inspection.updatedAt);
    
    // Get section status summary
    final sectionStatuses = widget.inspection.sectionStatus.values.toList();
    final hasInProgress = sectionStatuses.contains('in_progress');
    final hasPassed = sectionStatuses.contains('passed');
    final hasNotPassed = sectionStatuses.contains('not_passed');
    
    String completionStatus = 'No sections';
    if (sectionStatuses.isNotEmpty) {
      if (hasInProgress) {
        completionStatus = 'In Progress';
      } else if (hasPassed || hasNotPassed) {
        completionStatus = 'Completed';
      }
    }
    
    // Build sections details
    String sectionsDetails = '';
    if (widget.inspection.mechanicalRemarks.isNotEmpty || widget.inspection.mechanicalAssessment.isNotEmpty) {
      sectionsDetails += '• Mechanical Assessment:\n';
      if (widget.inspection.mechanicalRemarks.isNotEmpty) {
        sectionsDetails += '  Remarks: ${widget.inspection.mechanicalRemarks}\n';
      }
      if (widget.inspection.mechanicalAssessment.isNotEmpty) {
        sectionsDetails += '  Assessment: ${widget.inspection.mechanicalAssessment}\n';
      }
      sectionsDetails += '\n';
    }
    
    if (widget.inspection.lineGradeRemarks.isNotEmpty || widget.inspection.lineGradeAssessment.isNotEmpty) {
      sectionsDetails += '• Line and Grade Assessment:\n';
      if (widget.inspection.lineGradeRemarks.isNotEmpty) {
        sectionsDetails += '  Remarks: ${widget.inspection.lineGradeRemarks}\n';
      }
      if (widget.inspection.lineGradeAssessment.isNotEmpty) {
        sectionsDetails += '  Assessment: ${widget.inspection.lineGradeAssessment}\n';
      }
      sectionsDetails += '\n';
    }
    
    if (widget.inspection.architecturalRemarks.isNotEmpty || widget.inspection.architecturalAssessment.isNotEmpty) {
      sectionsDetails += '• Architectural Assessment:\n';
      if (widget.inspection.architecturalRemarks.isNotEmpty) {
        sectionsDetails += '  Remarks: ${widget.inspection.architecturalRemarks}\n';
      }
      if (widget.inspection.architecturalAssessment.isNotEmpty) {
        sectionsDetails += '  Assessment: ${widget.inspection.architecturalAssessment}\n';
      }
      sectionsDetails += '\n';
    }
    
    if (widget.inspection.civilStructuralRemarks.isNotEmpty || widget.inspection.civilStructuralAssessment.isNotEmpty) {
      sectionsDetails += '• Civil/Structural Assessment:\n';
      if (widget.inspection.civilStructuralRemarks.isNotEmpty) {
        sectionsDetails += '  Remarks: ${widget.inspection.civilStructuralRemarks}\n';
      }
      if (widget.inspection.civilStructuralAssessment.isNotEmpty) {
        sectionsDetails += '  Assessment: ${widget.inspection.civilStructuralAssessment}\n';
      }
      sectionsDetails += '\n';
    }
    
    if (widget.inspection.sanitaryPlumbingRemarks.isNotEmpty || widget.inspection.sanitaryPlumbingAssessment.isNotEmpty) {
      sectionsDetails += '• Sanitary/Plumbing Assessment:\n';
      if (widget.inspection.sanitaryPlumbingRemarks.isNotEmpty) {
        sectionsDetails += '  Remarks: ${widget.inspection.sanitaryPlumbingRemarks}\n';
      }
      if (widget.inspection.sanitaryPlumbingAssessment.isNotEmpty) {
        sectionsDetails += '  Assessment: ${widget.inspection.sanitaryPlumbingAssessment}\n';
      }
      sectionsDetails += '\n';
    }
    
    if (widget.inspection.electricalElectronicsRemarks.isNotEmpty || widget.inspection.electricalElectronicsAssessment.isNotEmpty) {
      sectionsDetails += '• Electrical/Electronics Assessment:\n';
      if (widget.inspection.electricalElectronicsRemarks.isNotEmpty) {
        sectionsDetails += '  Remarks: ${widget.inspection.electricalElectronicsRemarks}\n';
      }
      if (widget.inspection.electricalElectronicsAssessment.isNotEmpty) {
        sectionsDetails += '  Assessment: ${widget.inspection.electricalElectronicsAssessment}\n';
      }
      sectionsDetails += '\n';
    }
    
    if (sectionsDetails.isEmpty) {
      sectionsDetails = 'No inspection sections were completed.\n\n';
    }
    
    // Location information
    String locationInfo = 'Not available';
    if (widget.inspection.latitude != null && widget.inspection.longitude != null) {
      locationInfo = 'Lat: ${widget.inspection.latitude!.toStringAsFixed(8)}, Lng: ${widget.inspection.longitude!.toStringAsFixed(8)}';
    }
    
    // Timing information
    String timingInfo = '';
    if (widget.inspection.inspectionStartTime != null) {
      timingInfo += '• Start Time: ${_formatDateTime(widget.inspection.inspectionStartTime!)}\n';
    }
    if (widget.inspection.inspectionEndTime != null) {
      timingInfo += '• End Time: ${_formatDateTime(widget.inspection.inspectionEndTime!)}\n';
    }
    if (widget.inspection.inspectionStartTime != null && widget.inspection.inspectionEndTime != null) {
      timingInfo += '• Duration: ${_calculateDuration(widget.inspection.inspectionStartTime!, widget.inspection.inspectionEndTime!)}\n';
    }
    if (timingInfo.isEmpty) {
      timingInfo = 'No timing information available.\n';
    }
    
    return '''INSPECTION REPORT
=================

Report Generated: ${currentDate.toString()}
Inspector: $inspectorName
Inspector ID: ${_currentUser?.id ?? 'N/A'}

INSPECTION DETAILS
------------------
Inspection ID: ${widget.inspection.id.substring(widget.inspection.id.length - 8)}
Business ID: ${widget.inspection.scannedData}
Location: $locationInfo
Created: $createdDate
Updated: $updatedDate
User ID: ${widget.inspection.userId ?? 'N/A'}

INSPECTION SECTIONS
-------------------
$sectionsDetails
MEDIA FILES
-----------
• Photos: ${widget.inspection.imagePaths.length}
• Videos: ${widget.inspection.videoPaths.length}

TIMING INFORMATION
-----------------
$timingInfo
STATUS
------
• Sync Status: ${widget.inspection.isSynced ? 'Synced' : 'Pending'}
• Completion Status: $completionStatus

---
This report was generated by the OBO Mobile Inspector App.
For detailed information, please refer to the full inspection data in the mobile application.

Office of Building Official
Ormoc City
''';
  }

  String _formatDateTime(DateTime dateTime) {
    return '${dateTime.day}/${dateTime.month}/${dateTime.year} ${dateTime.hour.toString().padLeft(2, '0')}:${dateTime.minute.toString().padLeft(2, '0')}';
  }

  String _calculateDuration(DateTime start, DateTime end) {
    final duration = end.difference(start);
    final hours = duration.inHours;
    final minutes = duration.inMinutes % 60;

    if (hours > 0) {
      return '${hours}h ${minutes}m';
    } else {
      return '${minutes}m';
    }
  }

  Future<void> _sendEmail() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      // Check if running on web
      if (kIsWeb) {
        print('Running on web - using mailto');
        await _sendEmailViaWeb();
        return;
      }

      // Mobile platform - use flutter_email_sender
      final emailBody = await (widget.isDetailed ? _generateHtmlReport(detailed: true) : _generateHtmlReport(detailed: false));
      final Email email = Email(
        body: emailBody,
        subject: _buildEmailSubject(),
        recipients: _recipientsController.text.split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).toList(),
        cc: _ccController.text.split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).toList(),
        bcc: _bccController.text.split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).toList(),
        attachmentPaths: [
          ...widget.inspection.imagePaths,
          ...widget.inspection.videoPaths,
        ],
        isHTML: true,
      );

      print('Attempting to send email to: ${email.recipients}');
      await FlutterEmailSender.send(email);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Email client opened successfully! Please complete sending from your email app.'),
            backgroundColor: Color(0xFF10B981),
            duration: Duration(seconds: 3),
          ),
        );
        Navigator.of(context).pop();
      }
    } catch (e) {
      print('Email sending error: $e');
      if (mounted) {
        String errorMessage = 'Failed to open email client. ';
        
        if (e.toString().contains('MissingPluginException')) {
          errorMessage += 'Plugin not supported on web. Using web email method instead.';
          // Automatically try web method as fallback
          await _sendEmailViaWeb();
          return;
        } else if (e.toString().contains('No email client')) {
          errorMessage += 'Please install an email app like Gmail or Outlook.';
        } else if (e.toString().contains('permission')) {
          errorMessage += 'Please check app permissions.';
        } else {
          errorMessage += 'Error: $e';
        }
        
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(errorMessage),
            backgroundColor: Colors.red,
            duration: const Duration(seconds: 5),
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  

  Future<void> _sendEmailViaWeb() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      // Create mailto URL
      final recipients = _recipientsController.text.split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).join(',');
      final cc = _ccController.text.split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).join(',');
      final subject = Uri.encodeComponent(_buildEmailSubject());
      final body = Uri.encodeComponent(_generateTextReport(detailed: widget.isDetailed));
      
      String mailtoUrl = 'mailto:$recipients';
      List<String> params = [];
      
      if (subject.isNotEmpty) params.add('subject=$subject');
      if (body.isNotEmpty) params.add('body=$body');
      if (cc.isNotEmpty) params.add('cc=$cc');
      
      if (params.isNotEmpty) {
        mailtoUrl += '?${params.join('&')}';
      }
      
      print('Opening mailto URL: $mailtoUrl');
      
      final Uri emailUri = Uri.parse(mailtoUrl);
      if (await canLaunchUrl(emailUri)) {
        await launchUrl(emailUri);
        
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Email client opened via web! Please complete sending from your email app.'),
              backgroundColor: Color(0xFF10B981),
              duration: Duration(seconds: 3),
            ),
          );
          Navigator.of(context).pop();
        }
      } else {
        throw Exception('Could not launch email client');
      }
    } catch (e) {
      print('Web email sending error: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to open email client: $e'),
            backgroundColor: Colors.red,
            duration: const Duration(seconds: 5),
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  Future<List<String>> _inlineImageHtmlList() async {
    List<String> htmls = [];
    for (final path in widget.inspection.imagePaths) {
      try {
        String base64Str;
        String ext = path.split('.').last.toLowerCase();
        String mimeType = (ext == 'png')
          ? 'image/png'
          : (ext == 'jpg' || ext == 'jpeg'
              ? 'image/jpeg'
              : 'image/*');
        Uint8List bytes;
        if (kIsWeb) {
          // On web, assume path is a blob/DataUrl already!
          // We can't synchronously fetch raw bytes from web FileSystem.
          base64Str = path; // fallback display as img src
        } else {
          final file = File(path);
          if (!await file.exists()) continue;
          bytes = await file.readAsBytes();
          base64Str = base64Encode(bytes);
        }
        // On web base64Str may already be a dataUrl, else build it.
        final src = kIsWeb && path.startsWith('data:')
            ? path
            : 'data:$mimeType;base64,$base64Str';
        htmls.add('<div style="margin:6px 0"><img src="$src" style="max-width:170px; border-radius:8px; border:1px solid #e2e8f0; box-shadow:0 2px 10px #0002;" /><div style="font-size:12px; color:#666">${_escapeHtml(_basename(path))}</div></div>');
      } catch (e) {
        htmls.add('<div><span style="color:#ff0000">(Failed to attach image: ${_escapeHtml(_basename(path))})</span></div>');
      }
    }
    return htmls;
  }

  Future<List<String>> _inlineVideoList() async {
    // Embedding playable video isn't supported by email clients. So just list filenames, maybe thumbnail later.
    List<String> htmls = [];
    for (final path in widget.inspection.videoPaths) {
      htmls.add('<div style="margin:3px 0; color:#374151;"><span style="font-size:15px;">🎬 ${_escapeHtml(_basename(path))}</span></div>');
    }
    return htmls;
  }

  @override
  Widget build(BuildContext context) {
    final screenSize = MediaQuery.of(context).size;
    final isTablet = screenSize.width > 600;

    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      appBar: AppBar(
        title: Text(
          widget.isDetailed ? 'Send Detailed Report' : 'Send Quick Report',
          style: TextStyle(
            fontSize: isTablet ? 20 : 18,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
        backgroundColor: const Color(0xFF3B82F6),
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.white),
        actions: [
          if (_isLoading)
            const Padding(
              padding: EdgeInsets.all(16.0),
              child: SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(
                  strokeWidth: 2,
                  valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                ),
              ),
            )
          else
            TextButton(
              onPressed: _sendEmail,
              child: const Text(
                'Send',
                style: TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                  fontSize: 16,
                ),
              ),
            ),
        ],
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: EdgeInsets.all(isTablet ? 24 : 16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Inspection Info Card
              Container(
                width: double.infinity,
                padding: EdgeInsets.all(isTablet ? 20 : 16),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: const Color(0xFFE2E8F0), width: 1),
                  boxShadow: const [
                    BoxShadow(
                      color: Color(0xFFE2E8F0),
                      offset: Offset(0, 2),
                      blurRadius: 4,
                      spreadRadius: 0,
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Container(
                          padding: const EdgeInsets.all(8),
                          decoration: BoxDecoration(
                            color: const Color(0xFF3B82F6).withOpacity(0.1),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: const Icon(
                            Icons.assessment_rounded,
                            color: Color(0xFF3B82F6),
                            size: 20,
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                'Inspection Report',
                                style: TextStyle(
                                  fontSize: isTablet ? 18 : 16,
                                  fontWeight: FontWeight.bold,
                                  color: const Color(0xFF1F2937),
                                ),
                              ),
                              Text(
                                'ID: ${widget.inspection.id.substring(widget.inspection.id.length - 8)}',
                                style: TextStyle(
                                  fontSize: isTablet ? 12 : 10,
                                  color: const Color(0xFF6B7280),
                                  fontFamily: 'monospace',
                                ),
                              ),
                            ],
                          ),
                        ),
                        Container(
                          padding: EdgeInsets.symmetric(
                            horizontal: isTablet ? 12 : 8,
                            vertical: isTablet ? 6 : 4,
                          ),
                          decoration: BoxDecoration(
                            color: widget.isDetailed 
                                ? const Color(0xFF8B5CF6)
                                : const Color(0xFF10B981),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: Text(
                            widget.isDetailed ? 'Detailed' : 'Quick',
                            style: TextStyle(
                              fontSize: isTablet ? 12 : 10,
                              fontWeight: FontWeight.w600,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        _buildInfoChip('Photos', widget.inspection.imagePaths.length.toString(), Icons.photo_camera_rounded, isTablet),
                        const SizedBox(width: 8),
                        _buildInfoChip('Videos', widget.inspection.videoPaths.length.toString(), Icons.videocam_rounded, isTablet),
                        const SizedBox(width: 8),
                        _buildInfoChip('Status', widget.inspection.isSynced ? 'Synced' : 'Pending', 
                            widget.inspection.isSynced ? Icons.cloud_done_rounded : Icons.cloud_off_rounded, isTablet),
                      ],
                    ),
                  ],
                ),
              ),
              
              const SizedBox(height: 24),
              
              // Email Form
              Container(
                width: double.infinity,
                padding: EdgeInsets.all(isTablet ? 20 : 16),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: const Color(0xFFE2E8F0), width: 1),
                  boxShadow: const [
                    BoxShadow(
                      color: Color(0xFFE2E8F0),
                      offset: Offset(0, 2),
                      blurRadius: 4,
                      spreadRadius: 0,
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Email Details',
                      style: TextStyle(
                        fontSize: isTablet ? 18 : 16,
                        fontWeight: FontWeight.bold,
                        color: const Color(0xFF1F2937),
                      ),
                    ),
                    const SizedBox(height: 16),
                    
                    // Recipients
                    _buildTextField(
                      controller: _recipientsController,
                      label: 'Recipients',
                      hint: 'Enter email addresses (comma-separated)',
                      icon: Icons.email_outlined,
                      isRequired: true,
                      isTablet: isTablet,
                    ),
                    
                    const SizedBox(height: 16),
                    
                    // Subject
                    _buildTextField(
                      controller: _subjectController,
                      label: 'Subject',
                      hint: 'Enter email subject',
                      icon: Icons.subject_outlined,
                      isRequired: true,
                      isTablet: isTablet,
                    ),
                    
                    const SizedBox(height: 16),
                    
                    // CC
                    _buildTextField(
                      controller: _ccController,
                      label: 'CC (Optional)',
                      hint: 'Enter CC email addresses',
                      icon: Icons.copy_outlined,
                      isRequired: false,
                      isTablet: isTablet,
                    ),
                    
                    const SizedBox(height: 16),
                    
                    // BCC
                    _buildTextField(
                      controller: _bccController,
                      label: 'BCC (Optional)',
                      hint: 'Enter BCC email addresses',
                      icon: Icons.visibility_off_outlined,
                      isRequired: false,
                      isTablet: isTablet,
                    ),
                    
                    const SizedBox(height: 16),
                    
                    // Body
                    _buildTextField(
                      controller: _bodyController,
                      label: 'Message Body',
                      hint: 'Enter your message',
                      icon: Icons.message_outlined,
                      isRequired: true,
                      isTablet: isTablet,
                      maxLines: 8,
                    ),
                  ],
                ),
              ),
              
              const SizedBox(height: 24),
              
              // Attachments Section
              Container(
                width: double.infinity,
                padding: EdgeInsets.all(isTablet ? 20 : 16),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: const Color(0xFFE2E8F0), width: 1),
                  boxShadow: const [
                    BoxShadow(
                      color: Color(0xFFE2E8F0),
                      offset: Offset(0, 2),
                      blurRadius: 4,
                      spreadRadius: 0,
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        const Icon(
                          Icons.attach_file_rounded,
                          color: Color(0xFF3B82F6),
                          size: 20,
                        ),
                        const SizedBox(width: 8),
                        Text(
                          'Attachments',
                          style: TextStyle(
                            fontSize: isTablet ? 18 : 16,
                            fontWeight: FontWeight.bold,
                            color: const Color(0xFF1F2937),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    Text(
                      'After opening your email client, you can manually attach inspection photos and videos.',
                      style: TextStyle(
                        fontSize: isTablet ? 14 : 12,
                        color: const Color(0xFF6B7280),
                      ),
                    ),
                    if (widget.inspection.imagePaths.isNotEmpty || widget.inspection.videoPaths.isNotEmpty) ...[
                      const SizedBox(height: 12),
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: const Color(0xFFF0F9FF),
                          borderRadius: BorderRadius.circular(8),
                          border: Border.all(color: const Color(0xFF0EA5E9), width: 1),
                        ),
                        child: Row(
                          children: [
                            const Icon(
                              Icons.info_outline_rounded,
                              color: Color(0xFF0EA5E9),
                              size: 16,
                            ),
                            const SizedBox(width: 8),
                            Expanded(
                              child: Text(
                                'This inspection has ${widget.inspection.imagePaths.length} photos and ${widget.inspection.videoPaths.length} videos. You can attach them manually in your email client.',
                                style: TextStyle(
                                  fontSize: isTablet ? 12 : 10,
                                  color: const Color(0xFF0EA5E9),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ],
                ),
              ),
              
              const SizedBox(height: 32),
              
              // Send Buttons
              Column(
                children: [
                  // Primary Send Button
                  SizedBox(
                    width: double.infinity,
                    height: isTablet ? 56 : 48,
                    child: ElevatedButton.icon(
                      onPressed: _isLoading ? null : _sendEmail,
                      icon: _isLoading 
                          ? const SizedBox(
                              width: 20,
                              height: 20,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                              ),
                            )
                          : const Icon(Icons.send_rounded, color: Colors.white),
                      label: Text(
                        _isLoading ? 'Sending...' : 'Send Email',
                        style: TextStyle(
                          fontSize: isTablet ? 16 : 14,
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                      ),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: const Color(0xFF3B82F6),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        elevation: 0,
                      ),
                    ),
                  ),
                  
                  if (!kIsWeb) ...[
                    const SizedBox(height: 12),
                    
                    // Alternative Send Button (only show on mobile)
                    SizedBox(
                      width: double.infinity,
                      height: isTablet ? 48 : 44,
                      child: OutlinedButton.icon(
                        onPressed: _isLoading ? null : _sendEmailViaWeb,
                        icon: const Icon(Icons.web_rounded, color: Color(0xFF3B82F6)),
                        label: Text(
                          'Send via Web Email',
                          style: TextStyle(
                            fontSize: isTablet ? 14 : 12,
                            fontWeight: FontWeight.w600,
                            color: const Color(0xFF3B82F6),
                          ),
                        ),
                        style: OutlinedButton.styleFrom(
                          side: const BorderSide(color: Color(0xFF3B82F6), width: 1.5),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                    ),
                    
                    const SizedBox(height: 8),
                    
                    // Help text (only show on mobile)
                    Text(
                      'If the first option fails, try the web email option',
                      style: TextStyle(
                        fontSize: isTablet ? 12 : 10,
                        color: const Color(0xFF6B7280),
                        fontStyle: FontStyle.italic,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ] else ...[
                    const SizedBox(height: 8),
                    
                    // Help text for web
                    Text(
                      'Email will open in your default email client',
                      style: TextStyle(
                        fontSize: isTablet ? 12 : 10,
                        color: const Color(0xFF6B7280),
                        fontStyle: FontStyle.italic,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ],
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required String hint,
    required IconData icon,
    required bool isRequired,
    required bool isTablet,
    int maxLines = 1,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(icon, color: const Color(0xFF3B82F6), size: isTablet ? 18 : 16),
            const SizedBox(width: 8),
            Text(
              label,
              style: TextStyle(
                fontSize: isTablet ? 14 : 12,
                fontWeight: FontWeight.w600,
                color: const Color(0xFF374151),
              ),
            ),
            if (isRequired) ...[
              const SizedBox(width: 4),
              const Text(
                '*',
                style: TextStyle(
                  color: Colors.red,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ],
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          maxLines: maxLines,
          validator: isRequired ? (value) {
            if (value == null || value.trim().isEmpty) {
              return 'This field is required';
            }
            return null;
          } : null,
          decoration: InputDecoration(
            hintText: hint,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFFE2E8F0)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFF3B82F6), width: 2),
            ),
            contentPadding: EdgeInsets.symmetric(
              horizontal: isTablet ? 16 : 12,
              vertical: isTablet ? 16 : 12,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildInfoChip(String label, String value, IconData icon, bool isTablet) {
    return Container(
      padding: EdgeInsets.symmetric(
        horizontal: isTablet ? 12 : 8,
        vertical: isTablet ? 6 : 4,
      ),
      decoration: BoxDecoration(
        color: const Color(0xFFF0F9FF),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: const Color(0xFF0EA5E9), width: 1),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, color: const Color(0xFF0EA5E9), size: isTablet ? 14 : 12),
          const SizedBox(width: 4),
          Text(
            '$label: $value',
            style: TextStyle(
              fontSize: isTablet ? 12 : 10,
              fontWeight: FontWeight.w600,
              color: const Color(0xFF0EA5E9),
            ),
          ),
        ],
      ),
    );
  }
}
